# x. Model Inference

>Model yang sudah dilatih akan dicoba pada data yang bukan termasuk ke dalam train-set, val-set, ataupun test-set. Data ini harus dalam format yang asli, bukan data yang sudah di-scaled.

Pada bagian ini akan dilakukan proses model inference dengan menggunakan data `inference set` dan melakukan preprocessing yang sama seperti yang dilakukan sebelumnya serta melakukan prediksi terhadap data `inference-set`.

## Import Libraries

In [1]:
## REQUIRED LIBRARIES

# For load the files of model
import pickle

# For load model
from tensorflow.keras.models import load_model

# For data wrangling
import numpy as np  # linear algebra
import pandas as pd  # data processing

## Load model

In [2]:
# Load All Files of Functional API (Improvement)

with open('final_pipeline.pkl', 'rb') as file_1:
  final_pipeline = pickle.load(file_1)

model_ann = load_model('churn_risk_model.h5')

## Load data

In [3]:
# load data
df_inf = pd.read_csv('/content/data inference.csv')
df_inf

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,29,M,NaN,Silver Membership,No,Credit/Debit Card Offers,Desktop,Fiber_Optic,8.0,334.55,48523.56,14.0,788.580000,Yes,No,Yes,No Information Available,Poor Product Quality,0
1,38,F,Town,Premium Membership,No,Gift Vouchers/Coupons,Both,Fiber_Optic,14.0,294.47,34862.73,4.0,772.620000,Yes,Yes,No,Not Applicable,Quality Customer Care,0
2,35,M,City,Gold Membership,No,Without Offers,Both,Fiber_Optic,17.0,219.13,70247.76,3.0,1293.169381,Yes,Yes,No,Not Applicable,User Friendly Website,0
3,25,M,City,No Membership,NaN,Gift Vouchers/Coupons,NaN,Mobile_Data,11.0,206.97,11178.99,22.0,184.775450,No,Yes,Yes,Solved in Follow-up,Poor Product Quality,1
4,42,M,Village,Basic Membership,NaN,Without Offers,Desktop,Fiber_Optic,5.0,745.57,18074.30,11.0,631.880000,Yes,Yes,No,Not Applicable,Poor Product Quality,1
5,32,M,Town,Gold Membership,Yes,Credit/Debit Card Offers,Both,Mobile_Data,5.0,213.45,43547.33,8.0,793.350000,No,Yes,No,Not Applicable,User Friendly Website,0
6,60,M,NaN,Gold Membership,Yes,NaN,Desktop,Wi-Fi,13.0,167.42,7821.78,25.0,302.528047,Yes,No,Yes,Unsolved,No reason specified,0
7,16,F,City,Basic Membership,No,Without Offers,Desktop,Mobile_Data,19.0,78.80,36702.10,21.0,626.370000,Yes,No,No,Not Applicable,Too many ads,1
8,46,F,City,No Membership,Yes,Credit/Debit Card Offers,Smartphone,Wi-Fi,24.0,135.31,14597.55,17.0,585.230000,Yes,No,No,Not Applicable,Too many ads,1
9,54,M,City,Basic Membership,Yes,Credit/Debit Card Offers,Smartphone,Mobile_Data,NaN,225.95,30020.72,15.0,961.055804,Yes,Yes,Yes,No Information Available,Too many ads,1

In [4]:
# Transform Inference-Set

data_inf_transform = final_pipeline.transform(df_inf)
data_inf_transform

array([[0.48149906, 0.20876073, 0.4428433 , 5.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.34366902, 0.05964592, 0.43388064, 4.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        ],
       [0.70068393, 0.04473444, 0.72620584, 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        ],
       [0.10471349, 0.32805257, 0.10376445, 2.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.17428326, 0.16402629, 0.3548452 , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.43129171, 0.11929184, 0.44552199, 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        ],
       [0.07084114, 0.37278701, 0.16989084, 1.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.36222722, 0.31314109, 0.35175094, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        ],
       [0.13920483, 0.25349517, 0.32864793, 2.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        ],
       [0.29481588, 0.22367221, 0.53970063, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        ]])

In [12]:
# Predict using Artificial Neural Network

y_pred_inf = model_ann.predict(data_inf_transform)
y_pred_inf = np.where (y_pred_inf>=0.5, 1, 0)
y_pred_inf = pd.DataFrame(y_pred_inf, columns= ['churn_prediction'])
y_pred_inf

1/1 [==============================] - 0s 22ms/step

   churn_prediction
0                 0
1                 0
2                 0
3                 1
4                 1
5                 0
6                 0
7                 1
8                 1
9                 1

In [13]:
# concate `churn_risk_score` in data `df_inf` and the result of `y_pred_inf`
y = df_inf['churn_risk_score']
df_inf_final = pd.concat([y, y_pred_inf], axis=1)
df_inf_final

   churn_risk_score  churn_prediction
0                 0                 0
1                 0                 0
2                 0                 0
3                 1                 1
4                 1                 1
5                 0                 0
6                 0                 0
7                 1                 1
8                 1                 1
9                 1                 1

Berdasarkan dataFrame di atas, kita dapat mengetahui bagaimana keakuratan model memprediksi apakah seorang customer akan berhenti memakai produk yang ditawarkan atau tidak. Kita dapat melihat bahwa tidak ada perbedaan antara hasil prediksi dengan data aktual. Artinya, model ini sudah bagus untuk memprediksi seorang custumer akan churn atau tidak dan bisa digunakan oleh perusahaan untuk meminimalisir resiko customer churn.<br>
Hal ini dapat dibuktikan juga pada proses evaluasi model sebelumnya, kita mendapatkan bahwa model ini memiliki performansi terbaik mencapai `akurasi 92%` setelah dilakukan improvement.